import{a as m,S as q,i}from"./assets/vendor-DnoGfDwQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();m.defaults.baseURL="https://pixabay.com/api";const w="55642619-f9a4b7e30ea3503be8702d4a5",f=async(r,t)=>{const{data:a}=await m.get("/",{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return a},M=new q(".gallery a",{captionsData:"alt",captionDelay:250}),y=r=>{const t=r.map(({webformatURL:a,largeImageURL:l,tags:e,likes:o,views:n,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><span>Likes</span><span>${o}</span></p>
          <p><span>Views</span><span>${n}</span></p>
          <p><span>Comments</span><span>${v}</span></p>
          <p><span>Downloads</span><span>${S}</span></p>
        </div>
      </li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),M.refresh()},R=()=>{document.querySelector(".gallery").innerHTML=""},g=()=>{document.querySelector(".loader").classList.add("visible")},h=()=>{document.querySelector(".loader").classList.remove("visible")},L=()=>{document.querySelector(".load-more").classList.remove("is-hidden")},d=()=>{document.querySelector(".load-more").classList.add("is-hidden")},u={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},b=15;let c="",s=1,p=0;const B=async r=>{try{if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),!c)return;s=1,R(),d(),g();const t=await f(c,s);if(p=t.totalHits,t.hits.length===0){i.error({message:"No images found!",position:"topRight"});return}y(t.hits),s*b>=p?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(t){i.error({message:t.message,position:"topRight"})}finally{h()}},P=async()=>{try{s+=1,d(),g();const r=await f(c,s);y(r.hits);const t=u.gallery.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),s*b>=p?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(r){i.error({message:r.message,position:"topRight"})}finally{h()}};u.form.addEventListener("submit",B);u.loadMoreBtn.addEventListener("click",P);
//# sourceMappingURL=index.js.map
