import{a as u,S as b,i as p}from"./assets/vendor-DnoGfDwQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();u.defaults.baseURL="https://pixabay.com/api";const q="55642619-f9a4b7e30ea3503be8702d4a5",m=async(r,t)=>{const{data:a}=await u.get("/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return a},v=new b(".gallery a",{captionsData:"alt",captionDelay:250}),y=r=>{const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><span>Likes</span><span>${o}</span></p>
          <p><span>Views</span><span>${s}</span></p>
          <p><span>Comments</span><span>${L}</span></p>
          <p><span>Downloads</span><span>${S}</span></p>
        </div>
      </li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),v.refresh()},w=()=>{document.querySelector(".gallery").innerHTML=""},f=()=>{document.querySelector(".loader").classList.add("visible")},h=()=>{document.querySelector(".loader").classList.remove("visible")},M=()=>{document.querySelector(".load-more").classList.remove("is-hidden")},g=()=>{document.querySelector(".load-more").classList.add("is-hidden")},d={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),preloader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")};let l="",n=1,c=0;const B=async r=>{try{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l)return;n=1,w(),g(),f();const t=await m(l,n);if(c=t.totalHits,t.hits.length===0){p.error({message:"No images found!",position:"topRight"});return}y(t.hits),t.hits.length<c&&M()}catch(t){console.log(t)}finally{h()}},$=async()=>{try{n+=1,f();const r=await m(l,n);y(r.hits);const t=d.gallery.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),n*15>=c&&(g(),p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.log(r)}finally{h()}};d.form.addEventListener("submit",B);d.loadMoreBtn.addEventListener("click",$);
//# sourceMappingURL=index.js.map
